# ======================================================
# Hyunki 부품 ETL 파이프라인 설정
# - 공통 설정은 'common/*.yaml' 파일에서 관리됩니다.
# ======================================================

# S3 경로 설정 (버킷은 공통 설정 사용)
s3:
  source_prefix: "parts/hyunki" # 원본 HTML 저장 경로
  dest_prefix: "parts/hyunki"   # Parquet 결과물 저장 경로

# 웹 스크래핑(Fetcher) 관련 설정
fetcher:
  site:
    base: "https://hyunkistore.com/category"
    endpoints:
      - "/엔진/50/"
      # - "/트림/54/"
      # - "/전기장치/55/"
      # - "/미션/51/"
      # - "/샤시/52/"
      # - "/바디/53/"
      # - "/기타/57/"
    page_param: "page"
    start_page: 1
    max_pages: 1 # 테스트를 위해 1로 설정, 실제 운영 시 조정
    pause_between_categories_sec: 2.0
  requests:
    # hyunki.com 스크래핑 시 필요한 특정 헤더 (공통 헤더에 추가됨)
    headers:
      Referer: "https://hyunkistore.com/"
  delays:
    per_page_min_sec: 8.0
    per_page_max_sec: 12.0

# HTML 파싱(Spark Job) 관련 설정
parser:
  selectors:
    list_container: "ul.prdList.grid4"
    item_li: 'li[id^="anchorBoxId_"]'
    name_candidates:
      - ".description .name span"
      - ".name span"
    price_candidates:
      - ".price_all .pri"
      - ".price_all .strike"
      - ".price_all .custom"
    hidden_class: "displaynone"
  regex:
    part_code: "\\(([^)]+)\\)\\s*$" # 괄호 안의 부품 코드 추출
    price: "[\\d,]+"              # 가격(숫자, 콤마) 추출