# ======================================================
# Mobis 부품 ETL 파이프라인 설정
# - 공통 설정은 'common/*.yaml' 파일에서 관리됩니다.
# ======================================================

# S3 경로 설정 (버킷은 공통 설정 사용)
s3:
  prefix: "parts/mobis_parts" # 데이터 저장 경로

# 데이터베이스 테이블 설정
postgres:
  table_name: "mobis_parts"

# Fetcher (크롤러) 설정
fetcher:
  base_url: "https://www.mobis-as.com/simple_search_part.do"
  manufacturers: ["현대", "기아"]
  vehicle_types: ["승용", "상용"]
  part_keywords:
    - "엔진"
    - "오일"
    - "필터"
    - "라디에이터"
    - "냉각"
    - "워터펌프"
    - "벨트"
    - "체인"
    - "점화"
    - "플러그"
    - "코일"
    - "스로틀"
    - "흡기"
    - "배기"
    - "머플러"
    - "촉매"
    - "연료"
    - "인젝터"
    - "에어컨"
    - "컴프레서"
    - "콘덴서"
    - "히터"
    - "블로워"
    - "미션"
    - "변속기"
    - "클러치"
    - "샤프트"
    - "베어링"
    - "허브"
    - "브레이크"
    - "패드"
    - "로터"
    - "캘리퍼"
    - "호스"
    - "쇼크"
    - "댐퍼"
    - "스프링"
    - "로워암"
    - "컨트롤암"
    - "볼조인트"
    - "타이로드"
    - "스티어링"
    - "배터리"
    - "발전기"
    - "스타터"
    - "램프"
    - "헤드램프"
    - "테일램프"
    - "안개등"
    - "센서"
    - "범퍼"
    - "그릴"
    - "휀더"
    - "후드"
    - "도어"
    - "미러"
    - "유리"
    - "와이퍼"
    - "몰딩"
    - "가스켓"
    - "오링"
    - "브라켓"
    - "파이프"
    - "덕트"
    - "커버"

  timeouts:
    idle_timeout: 25 # Selenium 작업 대기 시간
  cooldowns:
    kw_cooldown: [2.0, 4.0]  # 키워드 변경 시 대기 시간
    page_pause: [1.2, 1.8]   # 페이지 이동 시 대기 시간

  # Mobis 스크래핑에 사용할 특정 User-Agent
  chrome_options:
    user_agents:
      - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Parser (Spark) 설정
parser:
  selectors:
    table_wrap: "#table-wrap div.table-list.sp-table"
    row_group: "ul.table-d"
    row: "li[role='row']"
    cell: "span.t-td[role='cell']"