# ======================================================
# Partsro 부품 ETL 파이프라인 설정
# - 공통 설정은 'common/*.yaml' 파일에서 관리됩니다.
# ======================================================

# S3 경로 설정 (버킷은 공통 설정 사용)
s3:
  source_prefix: "parts/partsro"
  dest_prefix: "parts/partsro"

# 웹 스크래핑(Fetcher) 관련 설정
fetcher:
  site:
    base_url: "https://m.partsro.com/"
    target_categories: ["엔진", "미션", "샤시", "바디", "트림"]
  xpaths:
    btn_all:
      - "//a[contains(.,'제품전체보기')]"
      - "//button[contains(.,'제품전체보기')]"
      - "//a[contains(.,'제품 전체보기')]"
      - "//button[contains(.,'제품 전체보기')]"
    category_template: "//a[normalize-space(text())='{cat}' or contains(.,'{cat}')]"
    load_more:
      - "//button[contains(.,'더보기') or contains(.,'더 보기')]"
      - "//a[contains(.,'더보기') or contains(.,'더 보기')]"

# HTML 파싱(Spark Job) 관련 설정
parser:
  selectors:
    card: "ul[class*='prd'] li, ul[class*='product'] li, div[class*='prd'] .item, div[class*='product'] .item, ul li"
  regex:
    price: '(\d[\d,]*)\s*원'
    price_only: '^\s*\d[\d,]*\s*원\s*$'
    code_in_paren: '\(([A-Z0-9-]{5,})\)'
    code_alnum_with_letter: '\b(?=[A-Z0-9-]{5,}\b)(?=.*[A-Z])[A-Z0-9-]+\b'
    code_numeric_long: '\b\d{8,}\b'