version: "3.1"
services:
  spark:
    build:
      context: .                 
      dockerfile: ./dockerfile.spark
    image: docker.io/joonlee0228/learn-apache-spark:3.5.3
    volumes:
      - ${SPARK_PROJ_DIR:-.}/data-pipeline/spark_jobs/:/opt/bitnami/spark/work
      - ${SPARK_PROJ_DIR:-.}/data-pipeline/spark_jobs/spark_conf/log4j2.properties:/opt/bitnami/spark/conf/log4j2.properties
      - ${SPARK_PROJ_DIR:-.}/data-pipeline/spark_jobs/spark_conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ${SPARK_PROJ_DIR:-.}/data-pipeline/spark_jobs/spark-events:/tmp/spark-events
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    user: "root"
    ports:
      - '8080:8080'
      - '18080:18080'
      - '4040:4040'

  spark-worker:
    build:
      context: .                 
      dockerfile: ./dockerfile.spark
    image: docker.io/joonlee0228/learn-apache-spark:3.5.3
    volumes:
      - ${SPARK_PROJ_DIR:-.}/data-pipeline/spark_jobs/working-dir:/opt/bitnami/spark/work
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    user: "root"