# ======================================================
# 웹 스크래핑 공통 설정
# - HTTP 요청(requests), 브라우저 자동화(Selenium) 기본값
# ======================================================

# requests 라이브러리 기반 Fetcher의 공통 설정
requests:
  # 기본 요청 타임아웃 (초)
  timeout: 20

  # 요청 실패 시 재시도 횟수
  retries: 3

  # 재시도 간격의 기본 배수 (backoff factor)
  backoff_base_sec: 1.8

  # 모든 요청에 포함될 기본 HTTP 헤더
  headers:
    Accept-Language: "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7"

  # 다양한 PC 환경의 User-Agent 리스트
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15"

# Selenium 기반 Fetcher의 공통 설정
selenium:
  # 페이지 로드를 기다리는 최대 시간 (초)
  page_load_timeout: 45

  # Chrome 드라이버에 적용할 공통 옵션
  chrome_options:
    headless: true
    disable_automation_flags: true

  # 다양한 모바일 환경의 User-Agent 리스트
  user_agents:
    - "Mozilla/5.0 (Linux; Android 14; Pixel 7 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Mobile Safari/537.36"
    - "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Mobile Safari/537.36"
    - "Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Mobile Safari/537.36"